
#!/bin/bash



# Colors for output

GREEN='\033[0;32m'

RED='\033[0;31m'

BLUE='\033[0;34m'

NC='\033[0m' # No Color



echo -e "${BLUE}###############################################${NC}"

echo -e "${BLUE}###    SavaPage Docker Deployment Master    ###${NC}"

echo -e "${BLUE}###############################################${NC}"

echo ""



# 1. Docker Check

if docker compose version >/dev/null 2>&1; then

    DOCKER_CMD="docker compose"

elif docker-compose version >/dev/null 2>&1; then

    DOCKER_CMD="docker-compose"

else

    echo -e "${RED}❌ No Docker Compose found. Please install it.${NC}"

    exit 1

fi



# 2. Setup Prompts

echo -e "${GREEN}--- Configuration ---${NC}"



read -p "SavaPage Version [1.6.0]: " VERSION

VERSION=${VERSION:-1.6.0}



read -p "HTTP Port (Web) [8631]: " HTTP_PORT

HTTP_PORT=${HTTP_PORT:-8631}



read -p "CUPS Port [631]: " CUPS_PORT

CUPS_PORT=${CUPS_PORT:-631}



echo -n "DB Password [savapage]: "

read -s DB_PASS

echo ""

DB_PASS=${DB_PASS:-savapage}



echo ""

echo -e "${GREEN}--- Storage Configuration ---${NC}"

echo "Where should the data be stored? (Absolute path or relative)"

echo "Example: /opt/savapage_data or ./data"

read -p "Storage Path [./volumes]: " STORAGE_PATH

STORAGE_PATH=${STORAGE_PATH:-./volumes}



# 3. Prepare Storage Folders

# We create them now to fix permissions, otherwise Docker creates them as root

echo -e "\n📂 Preparing storage directories at: ${BLUE}$STORAGE_PATH${NC}"

mkdir -p "$STORAGE_PATH/database"

mkdir -p "$STORAGE_PATH/custom"

mkdir -p "$STORAGE_PATH/data"

mkdir -p "$STORAGE_PATH/ext"

mkdir -p "$STORAGE_PATH/logs"

mkdir -p "$STORAGE_PATH/cups"



# Set permissions to ensure container users (postgres/savapage) can write

# (777 is easiest for docker setups to avoid UID mapping hell)

chmod -R 777 "$STORAGE_PATH"



# 4. Create .env

echo -e "\n📝 Generating configuration..."

cat > .env <<ENVEOF

# --- Automatically generated by build.sh ---

SP_VERSION=$VERSION

SP_HTTP_PORT=$HTTP_PORT

SP_CUPS_PORT=$CUPS_PORT

POSTGRES_USER=savapage

POSTGRES_PASSWORD=$DB_PASS

POSTGRES_DB=savapage

# Storage Path

SP_STORAGE_PATH=$STORAGE_PATH

# Static Vars

SAVAPAGE_NS=SP_

SP_CONTAINER=DOCKER

ENVEOF



# 5. Download Installer

FILENAME="savapage-setup-${VERSION}-final-linux-x64.bin"

URL="https://www.savapage.org/download/installer/${FILENAME}"



if [ ! -f "$FILENAME" ]; then

    echo -e "⬇️  Downloading installer ($VERSION)..."

    wget -q --show-progress -O "$FILENAME" "$URL"

    if [ $? -ne 0 ]; then

        echo -e "${RED}❌ Download failed!${NC}"

        exit 1

    fi

else

    echo "✅ Installer already exists."

fi



# 6. Build

echo -e "\n🐳 Building Docker Image..."

docker build \

  --build-arg INSTALLER_FILE="$FILENAME" \

  -t savapage . 2>&1 | tee ./build.log



if [ $? -ne 0 ]; then

    echo -e "${RED}❌ Build failed. Check build.log${NC}"

    exit 1

fi



# 7. Start

echo -e "\n🚀 Starting Container..."

$DOCKER_CMD down -v 2>/dev/null # Clean start

$DOCKER_CMD up -d



if [ $? -eq 0 ]; then

    SERVER_IP=$(hostname -I | awk '{print $1}')

    if [ -z "$SERVER_IP" ]; then SERVER_IP="127.0.0.1"; fi



    echo ""

    echo -e "${GREEN}✅ Deployment successful!${NC}"

    echo -e "${BLUE}------------------------------------------------${NC}"

    echo -e "Data Location: ${BLUE}${STORAGE_PATH}${NC}"

    echo -e "Web Interface: ${GREEN}http://${SERVER_IP}:${HTTP_PORT}${NC}"

    echo -e "CUPS Admin:    ${GREEN}http://${SERVER_IP}:${CUPS_PORT}${NC}"

    echo -e "${BLUE}------------------------------------------------${NC}"

else

    echo -e "${RED}❌ Startup failed.${NC}"

fi

