#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Reset Install State log
echo "# State file generated by installer.sh" > .install_state

echo -e "${BLUE}###############################################${NC}"
echo -e "${BLUE}###    SavaPage Docker Deployment Master    ###${NC}"
echo -e "${BLUE}###############################################${NC}"
echo ""

# 1. Docker Check
if docker compose version >/dev/null 2>&1; then
    DOCKER_CMD="docker compose"
elif docker-compose version >/dev/null 2>&1; then
    DOCKER_CMD="docker-compose"
else
    echo -e "${RED}❌ No Docker Compose found. Please install it.${NC}"
    exit 1
fi

# 2. Setup Prompts
echo -e "${GREEN}--- Configuration ---${NC}"

read -p "SavaPage Version [1.6.0]: " VERSION
VERSION=${VERSION:-1.6.0}

read -p "HTTP Port (Web) [8631]: " HTTP_PORT
HTTP_PORT=${HTTP_PORT:-8631}

read -p "CUPS Port [631]: " CUPS_PORT
CUPS_PORT=${CUPS_PORT:-631}

echo -n "DB Password [savapage]: "
read -s DB_PASS
echo ""
DB_PASS=${DB_PASS:-savapage}

echo ""
echo -e "${GREEN}--- Storage Configuration ---${NC}"
echo "Where should the data be stored? (Absolute path or relative)"
echo "Example: /opt/savapage_data or ./data"
read -p "Storage Path [./volumes]: " STORAGE_PATH
STORAGE_PATH=${STORAGE_PATH:-./volumes}

# 3. Prepare Storage Folders
echo -e "\n📂 Preparing storage directories at: ${BLUE}$STORAGE_PATH${NC}"
mkdir -p "$STORAGE_PATH/database"
mkdir -p "$STORAGE_PATH/custom"
mkdir -p "$STORAGE_PATH/data"
mkdir -p "$STORAGE_PATH/ext"
mkdir -p "$STORAGE_PATH/logs"
mkdir -p "$STORAGE_PATH/cups"

# Set permissions (777 is easiest for docker setups to avoid UID mapping hell)
chmod -R 777 "$STORAGE_PATH"


# 4. USB Printer Configuration & Check
echo ""
echo -e "${GREEN}--- USB Printer Configuration ---${NC}"
USB_DEVICES_YAML=""
SELECTED_DEVICE_NAMES=()

# Check if lsusb is installed
if ! command -v lsusb &> /dev/null; then
    echo -e "${YELLOW}⚠️  'lsusb' command not found.${NC}"
    read -p "Do you want to install 'usbutils' now? (requires root/sudo) (y/N): " INSTALL_LSUSB
    if [[ "$INSTALL_LSUSB" =~ ^[Yy]$ ]]; then
        echo "Installing usbutils..."
        apt-get update && apt-get install -y usbutils
        if [ $? -eq 0 ]; then
            # LOGGING FOR UNINSTALLER
            echo "INSTALLED_USBUTILS=true" >> .install_state
        else
            echo -e "${RED}❌ Installation failed. Skipping USB setup.${NC}"
        fi
    fi
fi

if command -v lsusb &> /dev/null; then
    read -p "Do you want to pass-through USB printers? (y/N): " SETUP_USB
    if [[ "$SETUP_USB" =~ ^[Yy]$ ]]; then
        
        echo -e "Scanning USB bus... (Please select your printers)"
        
        # Read lsusb output into an array line by line
        mapfile -t USB_LIST < <(lsusb)
        
        # Display list with index
        i=0
        for line in "${USB_LIST[@]}"; do
            echo "[$i] $line"
            ((i++))
        done
        
        echo ""
        echo "Enter the numbers of the devices you want to add, separated by space."
        echo "Example for multiple devices: 0 2 3"
        read -p "Selection: " USB_SELECTION

        if [ -n "$USB_SELECTION" ]; then
            # Start building the YAML block
            USB_DEVICES_YAML="    devices:"
            
            for index in $USB_SELECTION; do
                RAW_LINE="${USB_LIST[$index]}"
                
                if [ -n "$RAW_LINE" ]; then
                    # Extract Bus and Device numbers
                    BUS=$(echo "$RAW_LINE" | awk '{print $2}')
                    DEV=$(echo "$RAW_LINE" | awk '{print $4}' | tr -d ':')
                    # Get the name (everything after ID xxxx:xxxx)
                    NAME=$(echo "$RAW_LINE" | cut -d: -f3- | cut -d' ' -f2-)
                    
                    USB_PATH="/dev/bus/usb/$BUS/$DEV"
                    
                    echo -e "✅ Adding: ${BLUE}$USB_PATH${NC} ($NAME)"
                    
                    # Add to YAML string
                    USB_DEVICES_YAML="${USB_DEVICES_YAML}\n      - ${USB_PATH}:${USB_PATH}"
                    # Add to array for final output
                    SELECTED_DEVICE_NAMES+=("$NAME")
                fi
            done
        fi
    fi
else
    echo "Skipping USB setup (lsusb missing)."
fi


# 5. Create .env
echo -e "\n📝 Generating configuration..."
cat > .env <<ENVEOF
# --- Automatically generated by installer.sh ---
SP_VERSION=$VERSION
SP_HTTP_PORT=$HTTP_PORT
SP_CUPS_PORT=$CUPS_PORT
POSTGRES_USER=savapage
POSTGRES_PASSWORD=$DB_PASS
POSTGRES_DB=savapage
# Storage Path
SP_STORAGE_PATH=$STORAGE_PATH
# Static Vars
SAVAPAGE_NS=SP_
SP_CONTAINER=DOCKER
ENVEOF


# 6. Generate docker-compose.yml (Injecting USB_DEVICES_YAML)
echo "📝 Generating docker-compose.yml..."
cat > docker-compose.yml <<EOF
services:
  savapage:
    hostname: sp-server
    image: savapage
    container_name: savapage_savapage
    environment:
      - TZ=Europe/Berlin
      - SAVAPAGE_NS=\${SAVAPAGE_NS}
      - SP_CONTAINER=\${SP_CONTAINER}
      - SP_SRV_01=visitor.organization:My Company
      - SP_SRV_02=server.port:\${SP_HTTP_PORT}
      - SP_SRV_11=database.type:PostgreSQL
      - SP_SRV_12=database.driver:org.postgresql.Driver
      - SP_SRV_13=database.url:jdbc:postgresql://postgres:5432/\${POSTGRES_DB}
      - SP_SRV_14=database.user:\${POSTGRES_USER}
      - SP_SRV_15=database.password:\${POSTGRES_PASSWORD}
    ports:
      - "\${SP_CUPS_PORT}:631"
      - "\${SP_HTTP_PORT}:\${SP_HTTP_PORT}"
${USB_DEVICES_YAML}
    networks:
      - default
    depends_on:
      - postgres
    volumes:
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./init-savapage.sql:/docker-entrypoint-initdb.d/init.sql
      - \${SP_STORAGE_PATH:-./volumes}/custom:/opt/savapage/server/custom
      - \${SP_STORAGE_PATH:-./volumes}/data:/opt/savapage/server/data
      - \${SP_STORAGE_PATH:-./volumes}/ext:/opt/savapage/server/ext
      - \${SP_STORAGE_PATH:-./volumes}/logs:/opt/savapage/server/logs
      - \${SP_STORAGE_PATH:-./volumes}/cups:/etc/cups
    restart: unless-stopped

  postgres:
    hostname: sp-postgres
    image: postgres:15-alpine
    container_name: savapage_postgres
    environment:
      - POSTGRES_USER=\${POSTGRES_USER}
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
      - POSTGRES_DB=\${POSTGRES_DB}
    networks:
      - default
    volumes:
      - \${SP_STORAGE_PATH:-./volumes}/database:/var/lib/postgresql/data
      - ./init-savapage.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

networks:
  default:
    name: docker_savapage_network
    driver: bridge
EOF


# 7. Download Installer
FILENAME="savapage-setup-${VERSION}-final-linux-x64.bin"
URL="https://www.savapage.org/download/installer/${FILENAME}"

if [ ! -f "$FILENAME" ]; then
    echo -e "⬇️  Downloading installer ($VERSION)..."
    wget -q --show-progress -O "$FILENAME" "$URL"
    if [ $? -ne 0 ]; then
        echo -e "${RED}❌ Download failed!${NC}"
        exit 1
    fi
else
    echo "✅ Installer already exists."
fi


# 8. Build
echo -e "\n🐳 Building Docker Image..."
docker build \
  --build-arg INSTALLER_FILE="$FILENAME" \
  -t savapage . 2>&1 | tee ./build.log

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Build failed. Check build.log${NC}"
    exit 1
fi


# 9. Start
echo -e "\n🚀 Starting Container..."
$DOCKER_CMD down -v 2>/dev/null # Clean start
$DOCKER_CMD up -d

if [ $? -eq 0 ]; then
    SERVER_IP=$(hostname -I | awk '{print $1}')
    if [ -z "$SERVER_IP" ]; then SERVER_IP="127.0.0.1"; fi

    echo ""
    echo -e "${GREEN}✅ Deployment successful!${NC}"
    echo -e "${BLUE}------------------------------------------------${NC}"
    echo -e "Data Location: ${BLUE}${STORAGE_PATH}${NC}"
    echo -e "Web Interface: ${GREEN}http://${SERVER_IP}:${HTTP_PORT}${NC}"
    echo -e "CUPS Admin:    ${GREEN}http://${SERVER_IP}:${CUPS_PORT}${NC}"
    echo -e "${BLUE}------------------------------------------------${NC}"
    
    echo -e "${GREEN}--- Credentials ---${NC}"
    echo -e "SavaPage Web:  User: ${BLUE}admin${NC}      Pass: ${BLUE}admin${NC}"
    echo -e "CUPS Backend:  User: ${BLUE}savapage${NC}   Pass: ${BLUE}savapage${NC}"
    
    if [ ${#SELECTED_DEVICE_NAMES[@]} -gt 0 ]; then
        echo -e "${BLUE}------------------------------------------------${NC}"
        echo -e "${GREEN}--- Added USB Devices ---${NC}"
        for device in "${SELECTED_DEVICE_NAMES[@]}"; do
            echo -e "🔌 $device"
        done
    fi
    echo -e "${BLUE}------------------------------------------------${NC}"

else
    echo -e "${RED}❌ Startup failed.${NC}"
fi
